name: Build the content
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #       actions/checkout@v2
    - uses: actions/checkout@2036a08e25fa78bbd946711a407b529a0a1204bf
      name: "Check it out"
    - name: "Startup"
      run: pwd
    #       azure/docker-login latest with updated environment logic
    - uses: azure/docker-login@944f3176a9cfe29e1c53e92dff83e4f8c6eef52b
      name: "Connect to GitHub Packages"
      with:
        login-server: 'docker.pkg.github.com'
        username: ${{ secrets.READONLY_PACKAGE_SP }}
        password: ${{ secrets.READONLY_PACKAGE_TOKEN }}
    - name: "Build the site"
      run: |
        docker run -i -v ${PWD}:/usr/local/site docker.pkg.github.com/microsoft/opensource.microsoft.com/custom-jekyll-builder:latest sh << COMMANDS
        pwd && whoami
        cd /usr/local/site
        ls -la
        bundle install
        npm i
        ./node_modules/gulp/bin/gulp.js build
        JEKYLL_ENV=opensource.microsoft.com jekyll build
        COMMANDS
    - name: "Write content.json"
      env:
        GITSHA: ${{ github.sha }}
      run: |
          echo "{\"commitId\":\"$GITSHA\"}" > content.json
          cat ./content.json
          cp content.json _site/
    - name: "Compress the static site"
      run: zip -r ../site.zip .
      working-directory: /home/runner/work/opensource.microsoft.com/opensource.microsoft.com/_site
    #       actions/upload-artifact/v2
    - uses: actions/upload-artifact@58740802ef971a2d71eff71e63d48ab68d1f5507
      name: "Store the site as an artifact"
      with:
        name: website
        path: /home/runner/work/opensource.microsoft.com/opensource.microsoft.com/site.zip
    - name: "Connect to Azure Files"
      env:
        AZURE_FILES_ENDPOINT: ${{ secrets.AZURE_FILES_ENDPOINT }}
        AZURE_FILES_SP: ${{ secrets.AZURE_FILES_SP }}
        AZURE_FILES_USERNAME: ${{ secrets.AZURE_FILES_USERNAME }}
      run: |
        echo Making mountpoint /mnt/files
        sudo mkdir -p /mnt/files
        echo Preparing creds...
        if [ ! -d "/etc/smbcredentials" ]; then
          echo creating smb creds folder
          sudo mkdir /etc/smbcredentials
        fi
        echo Preparing share-specific creds...
        if [ ! -f "/etc/smbcredentials/files.cred" ]; then
          echo Storing share info...
          echo username=$AZURE_FILES_USERNAME >> ./files.cred
          echo password=$AZURE_FILES_SP >> ./files.cred
          sudo mv ./files.cred /etc/smbcredentials/
        fi
        echo Setting file mode...
        sudo chmod 600 /etc/smbcredentials/files.cred
        echo Writing to /etc/fstab
        echo Mounting...
        sudo mount -t cifs //$AZURE_FILES_ENDPOINT/dev /mnt/files -o vers=3.0,credentials=/etc/smbcredentials/files.cred,dir_mode=0777,file_mode=0777,serverino
    - name: "Copy site"
      working-directory: /home/runner/work/opensource.microsoft.com/opensource.microsoft.com
      run: |
        cp site.zip /mnt/files/
        cp content.json /mnt/files/
    - name: "Disconnect from Azure Files"
      run: |
        sudo umount /mnt/files
    - name: "Prepare to AzCopy..."
      working-directory: /home/runner/work
      run: |
        mkdir azcopy
        cd azcopy
        wget https://aka.ms/downloadazcopy-v10-linux
        mv downloadazcopy-v10-linux azcopy.tar.gz
        tar -xvf azcopy.tar.gz
        mv azcopy_linux* azcopy_linux
        mv azcopy_linux/azcopy ./
        ls -la
    - name: "Copy to CDN"
      working-directory: /home/runner/work/azcopy
      env:
        SASTOKEN: ${{ secrets.AZURE_CDN_SAS }}
      run: |
        ./azcopy sync /home/runner/work/opensource.microsoft.com/opensource.microsoft.com/_site "https://osssite.blob.core.windows.net/cdn/$SASTOKEN" --recursive=true
    - name: "Copy to static web container"
      working-directory: /home/runner/work/azcopy
      env:
        SASTOKEN: ${{ secrets.AZURE_WEB_SAS }}
      run: |
        ./azcopy sync /home/runner/work/opensource.microsoft.com/opensource.microsoft.com/_site "https://osssite.blob.core.windows.net/\$web/$SASTOKEN" --recursive=true
  
